### ISSUE TITLE
Create Hyper `HttpsConnector<SocksConnector<HttpConnector>>` with self signed certificate 

### ISSUE THREAD

**Issue by Masber** [ark0f/hyper-socks2#12]
Hi,

I have an HTTPS server with a self-signed certificate and my goal is to create a Hyper client using a `HttpsConnector<SocksConnector<HttpConnector>>` connector.

Dependencies:

```
hyper-socks2 = { version = "0.7.0", default-features = false, features = ["hyper-tls"] }
```

Then I do like this:

```
        let https_http_connector = config.rustls_https_connector()?;
        let mut http_connector = hyper::client::HttpConnector::new();
        http_connector.enforce_http(false);
        let socks_https_http_connector = SocksConnector {
            proxy_addr: std::env::var("SOCKS5").unwrap().parse::<Uri>().unwrap(), // scheme is required by HttpConnector
            auth: None,
            connector: https_http_connector.clone(),
        };
        // create HttpsConnector ????
        // inject server, CA and client certs ????
```

I noticed the `hyper-tls` feature does not provide the `with_tls` function.

But I don't know how to create HttpsConnector from the SocksConnector and inject the server, CA, and client certificate, any hints?

thank you very much

**Comment by ark0f** [comment]
> I noticed the hyper-tls feature does not provide the with_tls function.

You must use `tls` feature which is enabled by default, so `with_tls` function will be provided

**Comment by Masber** [comment]
ok, and how could I inject the CA root cert and the client cert (mutual TLS) into the HttpsConnector?

**Comment by ark0f** [comment]
```rust
let socks_connector = SocksConnector { ... };
let tls_connector = native_tls::TlsConnector::builder()
    .add_root_certificate(...)
    .build()?;
let https_connector = HttpsConnector::from(socks_connetor, tls_connector);
```
