### ISSUE TITLE
[Question] hyper-socks2 vs. async-socks5 ?

### ISSUE THREAD

**Issue by ohaddahan** [ark0f/hyper-socks2#18]
Both authored by @ark0f is it possible to explain the differences?
What should one use this over the other etc.?

**Comment by ark0f** [comment]
`async-socks5` is just client SOCKS5 implementation to be used on sockets.

`hyper-socks2` is built on `async-socks5` and created for `hyper` HTTP library

**Comment by ohaddahan** [comment]
Thanks!
